### ISSUE TITLE
Pretty_midi error

### ISSUE THREAD

**Issue by SubhasreeSengupta** [jsleep/wav2mid#1]
Hello, we are trying to run the pre-processing code. We were previously able to run it.
However, suddenly we are getting an error like : 
![pretty_midi error](https://user-images.githubusercontent.com/22556871/32999234-9c55930a-cd55-11e7-9813-cea1636bb63f.PNG)
Basically, it seems like a fluidsynth import error. 
Could you please suggest how to solve this issue? Thanks.

**Comment by jsleep** [comment]
You need to make sure you have fluidsynth installed on your system. On top of this I use this pyfluidsynth library to use fluidsynth in python. You may need to install an audio program like ffmpeg. Let me know if you try all three of these and it still doesn’t work.


Keep in mind this project is still in development so all code here should be used as reference and may not work out of the box for you.

**Comment by SubhasreeSengupta** [comment]
Thank you! We solved it.
